//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEjemplo2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mueble
    {
        public long Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<double> Largo { get; set; }
        public Nullable<double> Ancho { get; set; }
        public Nullable<double> Alto { get; set; }
        public Nullable<System.DateTime> FechaFabricacion { get; set; }
    }
}
